theme: jekyll-theme-time-machine
# brenjerman91.github.io
/*
Main page for all CIT Projects 

CIT 281 Spring 2021

Project 1
description- Explore the uses of terminal when creating folders. Then create code that outputs a string of random letters with a length between 5 and 25

Lab 1
description- Set up technology and create a node that carries out square roots and squares numbers


links

    Project 1
    https://brenjerman91.github.io/Project-1/

    lab 01
    https://brenjerman91.github.io/lab-01/


Project 2
description- Created a random string, rearrange characrters in ascending order, more practice with staging and committing changes on git through VS code.



Lab 2
description- Practice with git repositories
links

    Project 2
    https://brenjerman91.github.io/Project-2/
    
    lab 02
    https://brenjerman91.github.io/lab-02/


Project 3
description- Created a coinage code module that is capable of calculating the total value of coin objects. After completing the coinage code module functionality, them the server is updated the as a true Node.js web server using the Fastify package. The updated server file will display an initial web page with web links to to test the coinage code. The initial web page will be loaded from a file.



Lab 3
description- Practice with exporting fucntions 

Lab 4
description- Practice with creating servers 

links

    Project 3
    https://brenjerman91.github.io/Project-3/
    
    lab 03
    https://brenjerman91.github.io/lab-03/
    
    lab 04
    https://brenjerman91.github.io/lab-04/

Project 4
description- Gets 3 variables and displays them in different orders. These are then displayed on a server that can be viewed on the web. 

Lab 5
description- Practice with Postman 

Lab 6
description- Create a class that acts as a library for books 

links

    Project 4
    https://brenjerman91.github.io/Project-4/
    
    lab 05
    https://brenjerman91.github.io/lab-05/
    
    lab 06
    https://brenjerman91.github.io/lab-06/

Project 6
description- created shape classes that accept lenghts and then output the appropriate numbers based on perimeter and area

Lab 7 
description- Testing errors with by throwing them as well as creating custom errors

lab 8
description- Fetch info and display it on server

links-

    Project 6
    https://brenjerman91.github.io/Project-6/
    
    lab 07
    https://brenjerman91.github.io/lab-07/
    
    lab 08
    https://brenjerman91.github.io/lab-08/
    
    lab 09
    https://brenjerman91.github.io/lab-09/
   */

